/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CampaignsIndexRouteImport } from './routes/campaigns.index'
import { Route as CampaignsCampaignIdRouteImport } from './routes/campaigns.$campaignId'
import { Route as CampaignsCampaignIdApplyRouteImport } from './routes/campaigns.$campaignId.apply'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsIndexRoute = CampaignsIndexRouteImport.update({
  id: '/campaigns/',
  path: '/campaigns/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsCampaignIdRoute = CampaignsCampaignIdRouteImport.update({
  id: '/campaigns/$campaignId',
  path: '/campaigns/$campaignId',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsCampaignIdApplyRoute =
  CampaignsCampaignIdApplyRouteImport.update({
    id: '/apply',
    path: '/apply',
    getParentRoute: () => CampaignsCampaignIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/campaigns/$campaignId': typeof CampaignsCampaignIdRouteWithChildren
  '/campaigns/': typeof CampaignsIndexRoute
  '/campaigns/$campaignId/apply': typeof CampaignsCampaignIdApplyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/campaigns/$campaignId': typeof CampaignsCampaignIdRouteWithChildren
  '/campaigns': typeof CampaignsIndexRoute
  '/campaigns/$campaignId/apply': typeof CampaignsCampaignIdApplyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/campaigns/$campaignId': typeof CampaignsCampaignIdRouteWithChildren
  '/campaigns/': typeof CampaignsIndexRoute
  '/campaigns/$campaignId/apply': typeof CampaignsCampaignIdApplyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/campaigns/$campaignId'
    | '/campaigns/'
    | '/campaigns/$campaignId/apply'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/campaigns/$campaignId'
    | '/campaigns'
    | '/campaigns/$campaignId/apply'
  id:
    | '__root__'
    | '/'
    | '/campaigns/$campaignId'
    | '/campaigns/'
    | '/campaigns/$campaignId/apply'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CampaignsCampaignIdRoute: typeof CampaignsCampaignIdRouteWithChildren
  CampaignsIndexRoute: typeof CampaignsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/': {
      id: '/campaigns/'
      path: '/campaigns'
      fullPath: '/campaigns/'
      preLoaderRoute: typeof CampaignsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/$campaignId': {
      id: '/campaigns/$campaignId'
      path: '/campaigns/$campaignId'
      fullPath: '/campaigns/$campaignId'
      preLoaderRoute: typeof CampaignsCampaignIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/$campaignId/apply': {
      id: '/campaigns/$campaignId/apply'
      path: '/apply'
      fullPath: '/campaigns/$campaignId/apply'
      preLoaderRoute: typeof CampaignsCampaignIdApplyRouteImport
      parentRoute: typeof CampaignsCampaignIdRoute
    }
  }
}

interface CampaignsCampaignIdRouteChildren {
  CampaignsCampaignIdApplyRoute: typeof CampaignsCampaignIdApplyRoute
}

const CampaignsCampaignIdRouteChildren: CampaignsCampaignIdRouteChildren = {
  CampaignsCampaignIdApplyRoute: CampaignsCampaignIdApplyRoute,
}

const CampaignsCampaignIdRouteWithChildren =
  CampaignsCampaignIdRoute._addFileChildren(CampaignsCampaignIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CampaignsCampaignIdRoute: CampaignsCampaignIdRouteWithChildren,
  CampaignsIndexRoute: CampaignsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
