/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApplicationsRouteImport } from './routes/applications'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as BrandApplicantsRouteImport } from './routes/brand.applicants'
import { Route as CampaignsIndexRouteImport } from './routes/campaigns.index'
import { Route as CampaignsCampaignIdRouteImport } from './routes/campaigns.$campaignId'
import { Route as CollaborationsIndexRouteImport } from './routes/collaborations.index'
import { Route as CollaborationsCollabIdRouteImport } from './routes/collaborations.$collabId'
import { Route as BrandCampaignsIndexRouteImport } from './routes/brand.campaigns.index'
import { Route as CampaignsCampaignIdApplyRouteImport } from './routes/campaigns.$campaignId.apply'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsRoute = ApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandApplicantsRoute = BrandApplicantsRouteImport.update({
  id: '/brand/applicants',
  path: '/brand/applicants',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsIndexRoute = CampaignsIndexRouteImport.update({
  id: '/campaigns/',
  path: '/campaigns/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsCampaignIdRoute = CampaignsCampaignIdRouteImport.update({
  id: '/campaigns/$campaignId',
  path: '/campaigns/$campaignId',
  getParentRoute: () => rootRouteImport,
} as any)
const CollaborationsIndexRoute = CollaborationsIndexRouteImport.update({
  id: '/collaborations/',
  path: '/collaborations/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollaborationsCollabIdRoute = CollaborationsCollabIdRouteImport.update({
  id: '/collaborations/$collabId',
  path: '/collaborations/$collabId',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandCampaignsIndexRoute = BrandCampaignsIndexRouteImport.update({
  id: '/brand/campaigns/',
  path: '/brand/campaigns/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsCampaignIdApplyRoute =
  CampaignsCampaignIdApplyRouteImport.update({
    id: '/apply',
    path: '/apply',
    getParentRoute: () => CampaignsCampaignIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/brand/applicants': typeof BrandApplicantsRoute
  '/campaigns/$campaignId': typeof CampaignsCampaignIdRouteWithChildren
  '/collaborations/$collabId': typeof CollaborationsCollabIdRoute
  '/campaigns/': typeof CampaignsIndexRoute
  '/collaborations/': typeof CollaborationsIndexRoute
  '/campaigns/$campaignId/apply': typeof CampaignsCampaignIdApplyRoute
  '/brand/campaigns/': typeof BrandCampaignsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/brand/applicants': typeof BrandApplicantsRoute
  '/campaigns/$campaignId': typeof CampaignsCampaignIdRouteWithChildren
  '/collaborations/$collabId': typeof CollaborationsCollabIdRoute
  '/campaigns': typeof CampaignsIndexRoute
  '/collaborations': typeof CollaborationsIndexRoute
  '/campaigns/$campaignId/apply': typeof CampaignsCampaignIdApplyRoute
  '/brand/campaigns': typeof BrandCampaignsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/brand/applicants': typeof BrandApplicantsRoute
  '/campaigns/$campaignId': typeof CampaignsCampaignIdRouteWithChildren
  '/collaborations/$collabId': typeof CollaborationsCollabIdRoute
  '/campaigns/': typeof CampaignsIndexRoute
  '/collaborations/': typeof CollaborationsIndexRoute
  '/campaigns/$campaignId/apply': typeof CampaignsCampaignIdApplyRoute
  '/brand/campaigns/': typeof BrandCampaignsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/applications'
    | '/auth'
    | '/dashboard'
    | '/messages'
    | '/notifications'
    | '/profile'
    | '/brand/applicants'
    | '/campaigns/$campaignId'
    | '/collaborations/$collabId'
    | '/campaigns/'
    | '/collaborations/'
    | '/campaigns/$campaignId/apply'
    | '/brand/campaigns/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/applications'
    | '/auth'
    | '/dashboard'
    | '/messages'
    | '/notifications'
    | '/profile'
    | '/brand/applicants'
    | '/campaigns/$campaignId'
    | '/collaborations/$collabId'
    | '/campaigns'
    | '/collaborations'
    | '/campaigns/$campaignId/apply'
    | '/brand/campaigns'
  id:
    | '__root__'
    | '/'
    | '/applications'
    | '/auth'
    | '/dashboard'
    | '/messages'
    | '/notifications'
    | '/profile'
    | '/brand/applicants'
    | '/campaigns/$campaignId'
    | '/collaborations/$collabId'
    | '/campaigns/'
    | '/collaborations/'
    | '/campaigns/$campaignId/apply'
    | '/brand/campaigns/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApplicationsRoute: typeof ApplicationsRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  MessagesRoute: typeof MessagesRoute
  NotificationsRoute: typeof NotificationsRoute
  ProfileRoute: typeof ProfileRoute
  BrandApplicantsRoute: typeof BrandApplicantsRoute
  CampaignsCampaignIdRoute: typeof CampaignsCampaignIdRouteWithChildren
  CollaborationsCollabIdRoute: typeof CollaborationsCollabIdRoute
  CampaignsIndexRoute: typeof CampaignsIndexRoute
  CollaborationsIndexRoute: typeof CollaborationsIndexRoute
  BrandCampaignsIndexRoute: typeof BrandCampaignsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications': {
      id: '/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof ApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand/applicants': {
      id: '/brand/applicants'
      path: '/brand/applicants'
      fullPath: '/brand/applicants'
      preLoaderRoute: typeof BrandApplicantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/': {
      id: '/campaigns/'
      path: '/campaigns'
      fullPath: '/campaigns/'
      preLoaderRoute: typeof CampaignsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/$campaignId': {
      id: '/campaigns/$campaignId'
      path: '/campaigns/$campaignId'
      fullPath: '/campaigns/$campaignId'
      preLoaderRoute: typeof CampaignsCampaignIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collaborations/': {
      id: '/collaborations/'
      path: '/collaborations'
      fullPath: '/collaborations/'
      preLoaderRoute: typeof CollaborationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collaborations/$collabId': {
      id: '/collaborations/$collabId'
      path: '/collaborations/$collabId'
      fullPath: '/collaborations/$collabId'
      preLoaderRoute: typeof CollaborationsCollabIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand/campaigns/': {
      id: '/brand/campaigns/'
      path: '/brand/campaigns'
      fullPath: '/brand/campaigns/'
      preLoaderRoute: typeof BrandCampaignsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/$campaignId/apply': {
      id: '/campaigns/$campaignId/apply'
      path: '/apply'
      fullPath: '/campaigns/$campaignId/apply'
      preLoaderRoute: typeof CampaignsCampaignIdApplyRouteImport
      parentRoute: typeof CampaignsCampaignIdRoute
    }
  }
}

interface CampaignsCampaignIdRouteChildren {
  CampaignsCampaignIdApplyRoute: typeof CampaignsCampaignIdApplyRoute
}

const CampaignsCampaignIdRouteChildren: CampaignsCampaignIdRouteChildren = {
  CampaignsCampaignIdApplyRoute: CampaignsCampaignIdApplyRoute,
}

const CampaignsCampaignIdRouteWithChildren =
  CampaignsCampaignIdRoute._addFileChildren(CampaignsCampaignIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApplicationsRoute: ApplicationsRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  MessagesRoute: MessagesRoute,
  NotificationsRoute: NotificationsRoute,
  ProfileRoute: ProfileRoute,
  BrandApplicantsRoute: BrandApplicantsRoute,
  CampaignsCampaignIdRoute: CampaignsCampaignIdRouteWithChildren,
  CollaborationsCollabIdRoute: CollaborationsCollabIdRoute,
  CampaignsIndexRoute: CampaignsIndexRoute,
  CollaborationsIndexRoute: CollaborationsIndexRoute,
  BrandCampaignsIndexRoute: BrandCampaignsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
